name: "ashtree_cli"
description: "A command-line tool for help user build flutter project quickly."

version: 1.1.3

repository: https://github.com/bracebrace008/ashtree-cli-flutter

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter
  mason: ^0.1.0-dev.53
  path: ^1.9.0
  xml: ^6.5.0
  yaml: ^3.1.2
  translator: ^1.0.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.9

executables:
  ashtree_cli: main
include:
  - templates/**
